# Setup
title: Blog
url: https://ziasquinn.github.io/blog
paginate: 1
paginate_path: "/baseurl/page:num/"
baseurl: "/blog"
permalink: pretty
remote_theme: dark-poole

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Evelyn Marie
  url: https://twitter.com/zias_quinn
  email: evelyn<span>@</span>ziasquinn.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
